Feature/optional secondary
common-workflow-language/cwl-v1.1 pull request #4
Opened 2018-06-28 05:33 UTC by bogdang989

Pull request for the issue https://github.com/common-workflow-language/common-workflow-language/issues/717

2018-07-31 13:23 UTC, tetron requested changes

2018-07-31 13:23 UTC, tetron commented on Process.yml
> +          items: [string, Expression, SecondaryFileSchema]
Add "null" to items list.

2018-07-31 13:23 UTC, tetron commented on Process.yml
> +        must be included alongside the primary file.
"should be"

2018-07-31 13:23 UTC, tetron commented on Process.yml
> +          2. Append the remainder of the string to the end of the file path.
Document "?" syntax for optionals

2018-07-31 13:23 UTC, tetron commented on Process.yml
> +        unchanged File or Directory object taken from input as a secondaryFile.
The expression may return "null" in which case there is no secondaryFile from that expression.

2018-07-31 13:23 UTC, tetron commented on tests/docker-array-secondaryfiles.cwl
> +        required: false
Add test case for "?" syntax, and another test case with an expression which conditionally returns "null"

2018-09-10 11:01 UTC, bogdang989 commented on Process.yml
> +        unchanged File or Directory object taken from input as a secondaryFile.
I added this line, but somehow the conversation was not resolved automatically

2019-01-24 19:31 UTC, tetron approved these changes

2019-01-25 17:44 UTC, merged